# action.yml

name: "Dev Version Bumper"
description: "A GitHub Action to automate development version bumping for a Python project using Poetry or Pip-based version management."
branding:
  icon: "rocket"
  color: "blue"

runs:
  using: "docker"
  image: "./Dockerfile"
