name: Version Bump

on:
  push:
    branches:
      - develop

jobs:
  bump_version:
    if: ${{ !contains(github.event.head_commit.message, 'Bump version to') }} 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Run Version Bump Script
        run: |
          python3 scripts/hooks/bump_dev_version.py
