name: Version Bump

on:
  push:
    branches:
      - develop

permissions:
  contents: write  # Grants necessary write permissions to the token for git push and tag operations

jobs:
  bump_version:
    if: ${{ !contains(github.event.head_commit.message, 'Bump version to') }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository with GITHUB_TOKEN
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensures git push and tag operations are authenticated

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          pip install poetry

      # Step 4: Configure Git user
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Step 5: Set Git remote URL with GITHUB_TOKEN
      # This enables git commands to use GITHUB_TOKEN for authentication
      - name: Set up Git remote with token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin "https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"

      # Step 6: Run Version Bump Script
      - name: Run Version Bump Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 bump_dev_version.py
